### PR TITLE
HDR Support Added for NVENC

### PR DESCRIPTION
**Pull request by Revan654**
Added HDR flags for Max CLL, Max FALL and Master-Display to NVENC. Make sure you update to the latest version of NVENCc to run the new flags.

Nvidia SDK still doesn't contain all the required flags to create HDR10 compatible file.

### CODE REVIEW

**Comment by pwacooijmans** [comment]
Awesome job...keep up the good work :) and don't forget about chromaloc...it has been added as well :)

**Comment by Revan654** [comment]
Nvidia would need to update the SDK first before it can be applied to the encoder. I'm guessing there waiting for HDR10+ to apply any new changes so they can cover both HDR10 and HDR10+ at the same time.

There just way to many standards for HDR. We already have four. Which is already overkill.

**Comment by pwacooijmans** [comment]
That already happend

Op wo 6 jun. 2018 20:48 schreef Revan654 <notifications@github.com>:

**Comment by pwacooijmans** [comment]
Sec i will give you a link

Op wo 6 jun. 2018 20:53 schreef Pieter Cooijmans <pwacooijmans@gmail.com>:

**Comment by pwacooijmans** [comment]
https://drive.google.com/open?id=1cLaPUyt3csf9RhP7SNKkuPV4LRjpVnJi
However they want to hide their shame from the public so it's been deleted
:) (Need a sharp eye to catch this)

2018-06-06 20:53 GMT+02:00 Pieter Cooijmans <pwacooijmans@gmail.com>:

**Comment by pwacooijmans** [comment]
Oh and please don't lose it...it's the only proof this version exists

2018-06-06 20:57 GMT+02:00 Pieter Cooijmans <pwacooijmans@gmail.com>:

**Comment by pwacooijmans** [comment]
And it's my life insurance as well...cuz you never know these days :)

2018-06-06 20:59 GMT+02:00 Pieter Cooijmans <pwacooijmans@gmail.com>:

**Comment by pwacooijmans** [comment]
https://drive.google.com/open?id=1_hE55gIqvMX5a5VuhA0BG4HF-XTjNXqX
and here the proof I am bloody serious about this.

2018-06-06 21:01 GMT+02:00 Pieter Cooijmans <pwacooijmans@gmail.com>:

**Comment by pwacooijmans** [comment]
PS: the other la la land versions were made with 4.05

2018-06-06 21:15 GMT+02:00 Pieter Cooijmans <pwacooijmans@gmail.com>:

**Comment by pwacooijmans** [comment]
So IF you want to make sure I live to tell the tale, then you better make
bloody sure you keep those versions :)

2018-06-06 21:16 GMT+02:00 Pieter Cooijmans <pwacooijmans@gmail.com>:

**Comment by pwacooijmans** [comment]
I took 1 for the team, that's all I ask in return :)

2018-06-06 21:18 GMT+02:00 Pieter Cooijmans <pwacooijmans@gmail.com>:

**Comment by pwacooijmans** [comment]
In other words....I wouldn't trust 4.07 even if I got a million dollars
with it

2018-06-06 21:20 GMT+02:00 Pieter Cooijmans <pwacooijmans@gmail.com>:

**Comment by pwacooijmans** [comment]
Ever watched the imitation game? Great movie, except now it's just about 1
bit.

2018-06-06 21:32 GMT+02:00 Pieter Cooijmans <pwacooijmans@gmail.com>:

**Comment by Revan654** [comment]
Output without all the HDR metadata:

output
output mkv

With Proper Metadata: 

hdrmetadata
hdrmetadata info

Mediainfo isn't reporting all the color coordinate. Not if it can do that or not. Just strange nothing changes.

**Comment by pwacooijmans** [comment]
It used to do that about a year ago....however there isn't an interest to
make it easier to report these numbers for the sake of preventing people
from copying movies

Op do 7 jun. 2018 03:50 schreef Revan654 <notifications@github.com>:

**Comment by pwacooijmans** [comment]
Furthermore IF you are looking for a mediainfo version with the
masterdisplay colors...check for mpc-hc version 17.13...it has one build in

Op do 7 jun. 2018 11:53 schreef Pieter Cooijmans <pwacooijmans@gmail.com>:

**Comment by pwacooijmans** [comment]
I will put the version of mpc-be and mpc-hc in the same link as you got the
samples from

Op do 7 jun. 2018 11:56 schreef Pieter Cooijmans <pwacooijmans@gmail.com>:

**Comment by pwacooijmans** [comment]
They are now on the same link as the test samples

Op do 7 jun. 2018 om 12:13 schreef Pieter Cooijmans <pwacooijmans@gmail.com

**Comment by pwacooijmans** [comment]
You also wonder why mpc-hc quit?....hint hint....

Op do 7 jun. 2018 om 12:16 schreef Pieter Cooijmans <pwacooijmans@gmail.com

**Comment by pwacooijmans** [comment]
Don't go this road...you will not win :(

Op do 7 jun. 2018 om 12:17 schreef Pieter Cooijmans <pwacooijmans@gmail.com

**Comment by pwacooijmans** [comment]
some other team tried to hide it one version later....check the k-lite
codec pack. But the fact is that mpc-hc ceased to exist after version
1.7.13.

Op do 7 jun. 2018 om 12:24 schreef Pieter Cooijmans <pwacooijmans@gmail.com

**Comment by pwacooijmans** [comment]
And there is this dutch saying: A warned man counts for 2.

Op do 7 jun. 2018 om 12:29 schreef Pieter Cooijmans <pwacooijmans@gmail.com

**Comment by pwacooijmans** [comment]
Oh and btw 1 byte changes....from 1 to 0...the minimum luminance

**Comment by drSHLEFF** [comment]
в бан ебанько

**Comment by pwacooijmans** [comment]
Sorry I don't speak your language drSHLEFF

**Comment by pwacooijmans** [comment]
Oh and check the dutch news from sunday 3-6-2018
I knew there would be a hack attempt on one of our hospitals after making this statement. Cuz some hacker happend to agree with me. But he doesn't realise I don't support this in any way. Leave innocent people be.

**Comment by pwacooijmans** [comment]
That is 1 freaking day after I make the statement and 1 day before the 12:00 first of the month general air attack alarm test here in holland......don't you think that is a little too obvious?

**Comment by pwacooijmans** [comment]
I am just trying to open a discussion about the statement I made, since I personally think it would be one of the greatest inventions since the mri scan for the health and well being for the entire world.

**Comment by pwacooijmans** [comment]
And that's all.

**Comment by Revan654** [comment]
> It used to do that about a year ago....however there isn't an interest to make it easier to report these numbers for the sake of preventing people from copying movies

My data comes from my own personally created HDR content.

I will put this out there, CPU encoding is still superior in quality and options. NVenc advantage is it's speed.

The best thing to do in my opinion encoding is offload some of the filters to the GPU while the CPU still does the main compression.

**Comment by techok** [comment]
One important lacking is --no-open-gop and --repeat-headers,  and to fix the long files encoding crash using the --chromaloc 2 .

Also lacking --hdr --hdr-opt 

There are TVs like LG B6 that wont play any HDR file created by NVEncC , due probably to the lack of the no-opengop , repeat-headers?

**Comment by Revan654** [comment]
Along with AUD and HRD flags, Plus the need for both VBV flags which NVEnc only has access to one.

This is a very good guide for Colorgrading and Encoding to HDR10.

Link: https://www.mysterybox.us/blog/2016/10/27/hdr-video-part-5-grading-mastering-and-delivering-hdr

**Comment by pwacooijmans** [comment]
Thank you so much for that guide!!!!!! Amazing!!!!

Op ma 11 jun. 2018 21:21 schreef Revan654 <notifications@github.com>:

**Comment by lpaauw** [comment]
Can you make qsvencc better so we can choose more options like LA ICQ etc...?
you did a great job and maybe can take of where staxrip left us...

**Pull request closed without merging**
